### ISSUE TITLE
Kun jij hier een paar regels intro schrijven?

### ISSUE THREAD

**Issue by AmberdeWilde** [SIG-DT/handboek-digitaal-toetsen#5]
https://github.com/SIG-DT/handboek-digitaal-toetsen/blob/a4d58f0d4c94328b9681aab0e738f6cc739b2398/03-toetsvormen.qmd#L4

o	Misschien willen we bij toetsvormen ook iets zeggen over dat je een toetsvorm niet ‘zomaar’ uitkiest, maar kiest op basis van je visie, leeruitkomsten, leerdoelen of je toetsbeleid? Of is dat niet de scope van deze handleiding en zit dat in de pagina’s waar we aan linken misschien ook al voldoende?
o	Ik mis (ik denk bij toetsvormen) een korte tekst over leerwegonafhankelijk toetsen. Dat zou ook in de inleidende tekst opgenomen kunnen worden misschien? Het is natuurlijk niet per se een toetsvorm, maar ik vind eigenlijk wel dat er ergens in dit handboek iets over moet worden opgenomen? Of jullie niet?
o	Ik denk bij toetsvormen: ik mis beroepsproducten waar nu veel mee wordt gewerkt en iets over e-portfolio? Of is dat buiten de scope? En wat is dan precies de scope?

**Comment by AmberdeWilde** [comment]
In het dynamische landschap van het onderwijs evolueren ook de benaderingen van toetsen voortdurend. Een cruciale stap in dit proces is het kiezen van de juiste toetsvorm, een taak die vaak uitdagend blijkt te zijn voor docenten, vooral in het tijdperk van digitaal onderwijs. Om die reden is de Keuzetool Toetsen ontwikkeld. Naast deze tool verkennen we in dit hoofdstuk ook het concept van programmatisch toetsen, een holistische benadering die de volledige ontwikkeling van studenten centraal stelt.

**Comment by ShKlinkenberg** [comment]
He @AmberdeWilde

Ik heb je intro tekst toegevoegd. 

De toetsvormen gaan hier expliciet over de tool die is ontwikkeld. In die tool staat ook portfolio en beroepsproducten opgenomen. Zou je de tool nog even willen bekijken om te zien of onze beschrijvende tekst wel dekkend genoeg is. Omdat het zo geschreven is op de corona crisis lijkt de tool niet relevant als ik het zo lees. Misschien is dat ook zo, maar misschien ook niet.

**Comment by AmberdeWilde** [comment]
Nee hoor, prima zo denk ik!
