### ISSUE TITLE
referentie?

### ISSUE THREAD

**Issue by AmberdeWilde** [SIG-DT/handboek-digitaal-toetsen#8]
https://github.com/SIG-DT/handboek-digitaal-toetsen/blob/a4d58f0d4c94328b9681aab0e738f6cc739b2398/07-itembanken.qmd#L784

**Comment by ShKlinkenberg** [comment]
Ik weet hier zo snel geen bron voor te verzinnen. Lijkt me ook niet heel erg nodig.
